apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
spec:
  storageClassName: mongodb-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: "/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values:
          - minikube